/**
 * VoApps Tools v3.4.0 — Electron Preload
 *
 * WHAT THIS DOES
 * - Exposes a safe, minimal bridge to the renderer (index.html)
 * - Allows UI to:
 *    • open a file path on disk (CSV/log) via Electron shell.openPath()
 *    • ask main process for last artifact paths (csv/log) generated by server.js
 *    • check for updates
 *    • get database statistics
 *
 * SECURITY NOTES
 * - contextIsolation is ON and nodeIntegration is OFF in main.js
 * - We only expose the specific functions we need.
 */

const { contextBridge, ipcRenderer } = require('electron');

// Expose protected methods that allow the renderer process to use
// the ipcRenderer without exposing the entire object
contextBridge.exposeInMainWorld('voapps', {
  getLastArtifacts: () => ipcRenderer.invoke('get-last-artifacts'),
  openPath: (filePath) => ipcRenderer.invoke('open-path', filePath),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  openUpdateUrl: (url) => ipcRenderer.invoke('open-update-url', url),
  getDatabaseStats: () => ipcRenderer.invoke('get-database-stats'),
  quit: () => ipcRenderer.invoke('quit-app'),
  selectFolder: () => ipcRenderer.invoke('select-folder'),
  setZoom: (level) => ipcRenderer.invoke('set-zoom', level),
  getZoom: () => ipcRenderer.invoke('get-zoom')
});